In [13]:
online_version = False
import os
from IPython.display import clear_output, display
from Controller import Controller

if online_version:
    from google.colab import auth
    auth.authenticate_user()
    from GoogleDrive import GoogleDrive
    drive = GoogleDrive()
else:
    from LocalDrive import GoogleDrive
    drive = GoogleDrive()

clear_output()
controller = Controller(drive, online_version)
controller.start()

VBox(children=(VBox(children=(Dropdown(description='Component:', options=('Python Programming', 'Data Visualiz…

In [7]:
import pandas as pd
url = "https://github.com/muratfirat78/CPP_Datasets/raw/main/company_sales_data.csv"
df = pd.read_csv(url)
df.head()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600

In [8]:
url = "https://github.com/muratfirat78/CPP_Datasets/raw/main/auto.xlsx"
dfAuto = pd.read_excel(url)
dfAuto.head()

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [9]:
url = "https://github.com/muratfirat78/CPP_Datasets/raw/main/temp.csv"
dfTemp = pd.read_csv(url)
dfTemp.head()

                  timestamp  temperature
0  2015-03-20T21:00:00.000Z    23.951663
1  2015-03-20T22:00:00.000Z    23.072889
2  2015-03-20T23:00:00.000Z    22.270819
3  2015-03-21T00:00:00.000Z    21.339437
4  2015-03-21T01:00:00.000Z    20.101074

In [10]:
url = "https://github.com/muratfirat78/CPP_Datasets/raw/main/iris.csv"
dfIris = pd.read_csv(url)
dfIris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa